version: '3'

tasks:
  build:
    cmds:
      - go build -v -i main.go

  protogen:
    cmds:
      - protoc --proto_path=pkg/dht/proto --go_out=pkg/dht/proto/ --go_opt=paths=source_relative --go-grpc_out=pkg/dht/proto/ --go-grpc_opt=paths=source_relative pkg/dht/proto/dht.proto
